---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://0.0.0.0:3100/loki/api/v1/push
    tenant_id: tenant1

scrape_configs:
  - job_name: flog
    static_configs:
      - targets:
          - localhost
        labels:
          job: flog
          __path__: /path/to/flog.log
